replicaCount: 1

# Common settings for all services
common:
  imagePullPolicy: Never
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Backend Services
services:
  auth:
    image:
      repository: card-battle/auth-service
      tag: "latest"
    port: 8080
    resources: {}

  card:
    image:
      repository: card-battle/card-service
      tag: "latest"
    port: 8081
    resources: {}

  deck:
    image:
      repository: card-battle/deck-service
      tag: "latest"
    port: 8082
    resources: {}

  game:
    image:
      repository: card-battle/game-service
      tag: "latest"
    port: 8083
    resources: {}

  lobby:
    image:
      repository: card-battle/lobby-service
      tag: "latest"
    port: 8084
    resources: {}

  replay:
    image:
      repository: card-battle/replay-service
      tag: "latest"
    port: 8085
    resources: {}

  user:
    image:
      repository: card-battle/user-service
      tag: "latest"
    port: 8086
    resources: {}

# Frontend settings
frontend:
  image:
    repository: card-battle/frontend
    tag: "latest"
    pullPolicy: Never
  port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  config:
    apiBaseUrl: "/api"
    wsBaseUrl: "/ws"

# Service settings
service:
  type: ClusterIP

# Ingress settings
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: card-battle.local
      paths:
        - path: /api/auth(/|$)(.*)
          pathType: Prefix
          service: auth
          port: 8080
        - path: /api/cards(/|$)(.*)
          pathType: Prefix
          service: card
          port: 8081
        - path: /api/decks(/|$)(.*)
          pathType: Prefix
          service: deck
          port: 8082
        - path: /api/games(/|$)(.*)
          pathType: Prefix
          service: game
          port: 8083
        - path: /api/lobby(/|$)(.*)
          pathType: Prefix
          service: lobby
          port: 8084
        - path: /api/replays(/|$)(.*)
          pathType: Prefix
          service: replay
          port: 8085
        - path: /api/users(/|$)(.*)
          pathType: Prefix
          service: user
          port: 8086
        - path: /(.*)
          pathType: Prefix
          service: frontend
          port: 80

# TLS configuration (if needed)
tls: []
  # - secretName: card-battle-tls
  #   hosts:
  #     - card-battle.local 