name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    
    - name: Verify Go installation
      run: go version
    
    - name: Install Go dependencies
      working-directory: ./backend
      run: go mod download
    
    - name: Run Go tests
      working-directory: ./backend
      run: go test ./... -v
    
    - name: CI Check
      run: echo "Hello from CI!" 